application: wiseviz-freedomhack
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: app/index.html
  upload: app/(.*\.html)

- url: /favicon\.ico
  static_files: app/img/favicon.ico
  upload: app/img/favicon\.ico

- url: /(.*\.html)
  static_files: app/\1
  upload: app/(.*\.html)

- url: /(.*\.json)
  static_files: app/\1
  upload: app/(.*\.json)

- url: /css
  static_dir: app/css

- url: /img
  static_dir: app/img

- url: /js
  static_dir: app/js

- url: /lib
  static_dir: app/lib

- url: /partials
  static_dir: app/partials

- url: /files
  static_dir: app/files

#- url: /partials/admin.html
  #static_files: app/partials/admin.html
  #upload: app/partials/admin.html
  #login: admin

- url: /.*
  script: _go_app

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- misc/.*
